#pragma once
#include <QtWidgets/QMainWindow>
#include "ui_ide.h"
#include <qdialog.h>
#include <qpushbutton.h>
#include <QHBoxLayout>
#include <QVBoxLayout>
#include <qtextedit.h>
#include <qfiledialog.h>
#include <qmessagebox.h>
#include <qtextstream.h>
#include <qsyntaxhighlighter.h>
#include <qregexp.h>
#include <qprocess.h>
#include <qtextcodec.h>
#include <QKeyEvent>
#include <QPlainTextEdit>
#include <QObject>
#include <qpainter.h>
#include <QToolBox>
#include <QLineEdit>
#include <qsettings.h>
#include <QLabel>
#include <QCheckBox>

#include "setting.hpp"
#include "syntax.hpp"
#include "codeeditor.hpp"
#include "linenumberarea.hpp"
#include "ide.h"